
// Author Name : Kadir Emre Oto
// Student ID  : 150140032
// E-mail	   : otok@itu.edu.tr

#include <stdio.h>										// to standart input/output functions
#include <math.h>

int range1=0, range2=0, range3=0, range4=0, range5=0; 	// Defining Variables
int algo=0, num_samples, number;
long seed; double percent;

int digits(long number){								// recursive function to determine number of digits
	if (!number) return 0;								// if number is 0, return 0 (it is stopping point)
	return 1 + digits(number / 10);						// f(x) = 1 + f(x/10) [it is the general formula]
}

void mid_rng(long *seed){								// MID-PRNG Algorithm
	*seed *= *seed;										// calculate square of seed

	int d = digits(*seed);								// determine number of digits
	long divisor = pow(10, (d / 2) - 2);					// divisor is used to crop the seed from right side

	if (d > 5) *seed /= divisor;						// If number of digits is bigger than 5
	*seed %= 100000; 									// Get Last 5 Digits
}

void lsd_rng(long *seed){								// LSD-PRNG Algorithm
	*seed *= 73;										// Multiply Seed with 73
	*seed %= 100000;									// Get Last 5 Digits
}

void take_samples(){
	int i;
		for (i = 0; i < num_samples; ++i){				// execute the algorithm number of samples times
			if (algo == 1) mid_rng(&seed);				// call the function by reference
			else lsd_rng(&seed);

			number = seed % 500 + 1;					// find the modulo of recalculated seed

			if (number < 101) range1 ++;
			else if (number < 201) range2++;
			else if (number < 301) range3++;
			else if (number < 401) range4++;
			else if (number < 501) range5++;
		}
		if (algo == 1) printf("$ %d random numbers were generated by using MID-PRNG:\n", num_samples);
		else printf("$ %d random numbers were generated by using LSD-PRNG:\n", num_samples);
	}

void print_histogram(){
	int r, j;
	for (r=1; r < 6; r++){
		if (r == 1){
			printf("  ");
			percent = range1 * 100 / (double)num_samples;
		}
		else if (r == 2) percent = range2 * 100 / (double)num_samples;
		else if (r == 3) percent = range3 * 100 / (double)num_samples;
		else if (r == 4) percent = range4 * 100 / (double)num_samples;
		else if (r == 5) percent = range5 * 100 / (double)num_samples;

		printf("%d..%d: ", (r-1)*100+1, r*100);
		for (j=0; j < (int)percent; j++) printf("*");
		printf(" (%.2f%%)\n", percent);
	}
}

int main(){
	do {
		if (algo != 0) printf("$ Selection is wrong, please choose only 1 or 2\n$ ");
		else{
			printf("$ Which PRNG Algorithm?\n");
			printf(" 1. MID-PRNG\n 2. LSD-PRNG\n$ ");
		}
		scanf("%d", &algo);
	} while (algo != 1 && algo != 2);		// to be sure the selection is 1 or 2

	do {
		printf("$ Enter the seed\n$ ");
		scanf("%ld", &seed);
	} while ((9999 >= seed || seed >= 100000) || (algo == 2 && (seed % 5 == 0 || seed % 2 == 0)));

	do {
		printf("$ Enter Number of Samples\n$ ");
		scanf("%d", &num_samples);
	} while (num_samples <= 0);

	take_samples();
	print_histogram();
	return 0;
}
